import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const roboto = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-roboto",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Dr. Sobhi Wazzan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images/logo.png" color="black" sizes="any" />
      </head>
      <body className={`${roboto.variable} antialiased`}>
        <Header />

        {children}
        <Footer />
      </body>
    </html>
  );
}
